declaraciones/declaraciones/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls import include, url
from declaracion import urls
from sitio import urls


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('declaracion/', include('declaracion.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

declaraciones/sitio/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy, re_path

from sitio.views import LoginView, LogoutView, CambioPasswordView, PasswordResetRFCView,activar
from .views import (IndexView, FAQsView, InformacionView,
                    DeclaracionesPreviasView,
                    DeclaracionesPreviasDescargarView)
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('preguntas-frecuentes', FAQsView.as_view(), name="preguntas-frecuentes"),
    path('informacion', InformacionView.as_view(), name="informacion"),
    path('declaraciones-previas', DeclaracionesPreviasView.as_view(), name="declaraciones-previas"),
    re_path(r'^declaraciones-previas/descargar/(?P<folio>[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})/$',
            DeclaracionesPreviasDescargarView.as_view(),
            name="declaraciones-previas-descargar"),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('recuperar', LogoutView.as_view(), name="recuperar"),
    path('cambiar', CambioPasswordView.as_view(), name="cambiar"),
    path('password_reset/', PasswordResetRFCView.as_view(success_url=reverse_lazy('password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^activar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activar, name='activar')
]

declaraciones/declaracion/forms/registro.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.forms import PasswordInput, DateInput
from django.core import exceptions

from declaracion.models import InfoPersonalVar
from declaracion.models.catalogos import CatPaises, CatEntidadesFederativas, CatEntesPublicos
from bootstrap_datepicker_plus import DatePickerInput
import django.contrib.auth.password_validation as validators


class RegistroForm(forms.Form):

    nombres = forms.CharField(required = True,label="Nombre(s)")
    apellido1 = forms.CharField(required = True,label="Primer apellido")
    apellido2 = forms.CharField(required = False,label="Segundo apellido")
    dependencia = forms.ModelChoiceField(queryset=CatEntesPublicos.objects.all(),required = True,label="Ente público")
    telefono = forms.CharField(max_length=15,required = True,label="Teléfono",validators=[RegexValidator('^\+?1?\d{9,10}$', message="Introduzca un Teléfono válido")])
    puesto = forms.CharField(required = True,label="Empleo, cargo o comisión")
    rfc = forms.CharField(max_length=13, label="RFC con Homoclave", required=True,validators=[RegexValidator('^([A-Z,Ñ,&]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[A-Z|\d]{3})$', message="Introduzca un RFC válido")])
    curp = forms.CharField(max_length=20, label="CURP (si aplica)", required=False,validators=[RegexValidator('^[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM]{1}(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{1}[0-9]{1}$', message="Introduzca un CURP válido")])
    fecha = forms.DateField(required=True, widget=DatePickerInput(options={
        "format":'YYYY-MM-DD',
        "locale":"es",
        "ignoreReadonly":True,
        "maxDate": 'now'
    }), label="Fecha de ingreso")
    email = forms.EmailField(required=True, label="Correo electrónico")
    contrasena1 = forms.CharField(widget=PasswordInput,required=True, label="Contraseña")
    contrasena2 = forms.CharField(widget=PasswordInput,required=True, label="Confirmar contraseña")

    pais = forms.ModelChoiceField(queryset=CatPaises.objects.all(),required=False,label="País de origen")
    entidad = forms.ModelChoiceField(queryset=CatEntidadesFederativas.objects.all(),required=False,label="Entidad Federativa")

    def clean(self):
        super().clean()
        email = self.cleaned_data.get("email")
        email = str(email).lower()
        if User.objects.filter(email = email).count()>0:
            self.add_error("email","Correo ya registrado")

        rfc = self.cleaned_data.get("rfc")
        rfc = str(rfc).upper()
        if User.objects.filter(username = rfc).count()>0:
            self.add_error("rfc","RFC ya registrado")

        c1 = self.cleaned_data.get('contrasena1')
        c2 = self.cleaned_data.get('contrasena2')



        if c1 != c2:
            self.add_error('contrasena1','Contraseñas no coinciden')
        if c1 is  None or  c1=="":
            self.add_error('contrasena1', 'Debes escribir una contraseña')
        else:
            try:
                 print(self.cleaned_data.get('contrasena1'))
                 validators.validate_password(password=self.cleaned_data.get('contrasena1'), user=User)
            except exceptions.ValidationError as e:

                 self.errors['contrasena1'] = list(e.messages)

class CambioEntePublicoForm(forms.Form):
    dependencia = forms.ModelChoiceField(queryset=CatEntesPublicos.objects.all(), required=True, label="Ente público")

declaraciones/declaracion/views/activos.py
import uuid
from django.urls import resolve
from django.views import View
from django.shortcuts import render, redirect
from django.forms.models import model_to_dict
from django.http import HttpResponseRedirect, Http404
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from declaracion.models import (Declaraciones, SeccionDeclaracion,
                                BienesMuebles, MueblesNoRegistrables,
                                BienesInmuebles, MueblesNoRegistrables,
                                Inversiones, EfectivoMetales, Fideicomisos,
                                BienesIntangibles, CuentasPorCobrar,
                                BeneficiosEspecie, ActivosBienes,
                                BienesPersonas, InfoPersonalVar,
                                Secciones, SeccionDeclaracion)
from declaracion.forms import (BienesMueblesForm, BienesInmueblesForm,
                               MueblesNoRegistrablesForm, InversionesForm,
                               EfectivoMetalesForm, FideicomisosForm,
                               BienesIntangiblesForm, CuentasPorCobrarForm,
                               BeneficiosEspecieForm, BienesPersonasForm,
                               ActivosBienesForm, InfoPersonalVarForm,
                               DomiciliosForm, ObservacionesForm)

from .declaracion import (DeclaracionDeleteView)
from .utils import (guardar_estatus, no_aplica, declaracion_datos,
                    validar_declaracion,obtiene_avance)


class BienesMueblesDeleteView(DeclaracionDeleteView):
    model = BienesMuebles


class BienesMueblesView(View):
    template_name = 'declaracion/activos/bienes-muebles.html'

    @method_decorator(login_required(login_url='/login'))
    def get(self, request, *args, **kwargs):
        folio_declaracion = self.kwargs['folio']
        avance, faltas = 0, None

        try:
            declaracion = validar_declaracion(request, folio_declaracion)
            avance, faltas = obtiene_avance(declaracion)
        except:
            raise Http404()

        info_personal_var = InfoPersonalVar.objects.filter(
            declaraciones=declaracion,
            cat_tipo_persona_id=InfoPersonalVar.TIPO_DECLARANTE
        ).first()

        agregar, editar_id, bienes_muebles_data, informacion_registrada = (
            declaracion_datos(kwargs, BienesMuebles, declaracion)
        )

        if bienes_muebles_data:
            activos_bienes = ActivosBienes.objects.filter(
                declaraciones=declaracion,
                cat_activo_bien_id=ActivosBienes.BIENES_MUEBLES,
            ).first()
            observaciones_data = bienes_muebles_data.observaciones
            bienes_muebles_data = model_to_dict(bienes_muebles_data)
            observaciones_data = model_to_dict(observaciones_data)

            declarante_bienes_personas = BienesPersonas.objects.filter(
                activos_bienes=activos_bienes,
                cat_tipo_participacion_id=BienesPersonas.DECLARANTE,
            ).first()

            if declarante_bienes_personas:
                bienes_personas_data = model_to_dict(declarante_bienes_personas)
            else:
                bienes_personas_data = {}

            copropietario_bienes_personas = BienesPersonas.objects.filter(
                activos_bienes=activos_bienes,
                cat_tipo_participacion_id=BienesPersonas.COPROPIETARIO,
            ).first()
            if copropietario_bienes_personas:
                copropietario_data = copropietario_bienes_personas.otra_persona
                copropietario_data = model_to_dict(copropietario_data)
            else:
                copropietario_data = {}

            propietario_anterior_bienes_personas = BienesPersonas.objects.filter(
                activos_bienes=activos_bienes,
                cat_tipo_participacion_id=BienesPersonas.PROPIETARIO_ANTERIOR,
            ).first()
            if propietario_anterior_bienes_personas:
                propietario_anterior_data = propietario_anterior_bienes_personas.otra_persona
                propietario_anterior_data = model_to_dict(propietario_anterior_data)
            else:
                propietario_anterior_data = {}

        else:
            bienes_muebles_data = {}
            observaciones_data = {}
            bienes_personas_data = {}
            copropietario_data = {}
            propietario_anterior_data = {}

        bienes_muebles_form = BienesMueblesForm(
            prefix="bienes_muebles",
            initial=bienes_muebles_data)
        observaciones_form = ObservacionesForm(
            prefix="observaciones",
            initial=observaciones_data)
        bienes_personas_form = BienesPersonasForm(
            prefix="bienes_personas",
            initial=bienes_personas_data)
        copropietario_form = InfoPersonalVarForm(
            prefix="copropietario",
            initial=copropietario_data)
        propietario_anterior_form = InfoPersonalVarForm(
            prefix="propietario_anterior",
            initial=propietario_anterior_data)

        return render(request, self.template_name, {
            'bienes_muebles_form': bienes_muebles_form,
            'observaciones_form': observaciones_form,
            'bienes_personas_form': bienes_personas_form,
            'copropietario_form': copropietario_form,
            'propietario_anterior_form': propietario_anterior_form,
            'folio_declaracion': folio_declaracion,
            'avance':avance,
            'faltas':faltas,
            'informacion_registrada': informacion_registrada,
            'agregar': agregar,
            'editar_id': editar_id
        })

    @method_decorator(login_required(login_url='/login'))
    def post(self, request, *args, **kwargs):
        folio_declaracion = self.kwargs['folio']

        try:
            declaracion = validar_declaracion(request, folio_declaracion)
        except:
            raise Http404()

        info_personal_var = InfoPersonalVar.objects.filter(
            declaraciones=declaracion,
            cat_tipo_persona_id=InfoPersonalVar.TIPO_DECLARANTE
        ).first()

        agregar, editar_id, bienes_muebles_data, informacion_registrada = (
            declaracion_datos(kwargs, BienesMuebles, declaracion)
        )

        if bienes_muebles_data:
            activos_bienes = ActivosBienes.objects.filter(
                declaraciones=declaracion,
                cat_activo_bien_id=ActivosBienes.BIENES_MUEBLES,
            ).first()
            observaciones_data = bienes_muebles_data.observaciones
            declarante_bienes_personas = BienesPersonas.objects.filter(
                activos_bienes=activos_bienes,
                cat_tipo_participacion_id=BienesPersonas.DECLARANTE,
            ).first()

            if declarante_bienes_personas:
                bienes_personas_data = declarante_bienes_personas
            else:
                bienes_personas_data = None

            copropietario_bienes_personas = BienesPersonas.objects.filter(
                activos_bienes=activos_bienes,
                cat_tipo_participacion_id=BienesPersonas.COPROPIETARIO,
            ).first()
            if copropietario_bienes_personas:
                copropietario_data = copropietario_bienes_personas.otra_persona
            else:
                copropietario_data = None

            propietario_anterior_bienes_personas = BienesPersonas.objects.filter(
                activos_bienes=activos_bienes,
                cat_tipo_participacion_id=BienesPersonas.PROPIETARIO_ANTERIOR,
            ).first()
            if propietario_anterior_bienes_personas:
                propietario_anterior_data = propietario_anterior_bienes_personas.otra_persona
            else:
                propietario_anterior_data = None
        else:
            bienes_muebles_data = None
            observaciones_data = None
            bienes_personas_data = None
            copropietario_data = None
            propietario_anterior_data = None

        bienes_muebles_form = BienesMueblesForm(
            request.POST,
            prefix="bienes_muebles",
            instance=bienes_muebles_data)
        observaciones_form = ObservacionesForm(
            request.POST,
            prefix="observaciones",
            instance=observaciones_data)
        bienes_personas_form = BienesPersonasForm(
            request.POST,
            prefix="bienes_personas",
            instance=bienes_personas_data)
        copropietario_form = InfoPersonalVarForm(
            request.POST,
            prefix="copropietario",
            instance=copropietario_data)
        propietario_anterior_form = InfoPersonalVarForm(
            request.POST,
            prefix="propietario_anterior",
            instance=propietario_anterior_data)

        if (
            bienes_muebles_form.is_valid() and
            observaciones_form.is_valid() and
            bienes_personas_form.is_valid() and
            copropietario_form.is_valid() and
            propietario_anterior_form.is_valid()
            ):

            activos_bienes, created = ActivosBienes.objects.get_or_create(
                declaraciones=declaracion,
                cat_activo_bien_id=ActivosBienes.BIENES_MUEBLES,
            )

            bienes_muebles = bienes_muebles_form.save(commit=False)
            observaciones = observaciones_form.save()

            propietario_anterior = propietario_anterior_form.save(commit=False)
            propietario_anterior.declaraciones = declaracion
            propietario_anterior.cat_tipo_persona_id = InfoPersonalVar.TIPO_PROPIETARIO_ANTERIOR
            propietario_anterior.save()

            copropietario = copropietario_form.save(commit=False)
            copropietario.declaraciones = declaracion
            copropietario.cat_tipo_persona_id = InfoPersonalVar.TIPO_COPROPIETARIO
            copropietario.save()

declaraciones/declaracion/views/declaracion.py
import uuid
import json
from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView
from django.http import Http404, JsonResponse
from declaracion.models import Declaraciones,InfoPersonalFija
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Q

class DeclaracionView(TemplateView):
    template_name = "declaracion/index.html"
    @method_decorator(login_required(login_url='/login'))
    def get(self,request,*args,**kwargs):
        try:
            declaracion = Declaraciones.objects.filter(
                info_personal_fija=InfoPersonalFija.objects.filter(usuario=request.user).first()).filter(
                Q(cat_estatus__isnull=True) | Q(cat_estatus__pk__in=(1, 2, 3))).first()

        except:
            declaracion = None

        return render(request,self.template_name,{'declaracion':declaracion})


class DeclaracionDeleteView(DeleteView):
    def get(self, request, *args,**kwargs):
        raise Http404("")

    def get_object(self, queryset=None):
        try:
            folio_declaracion = self.kwargs['folio']
            pk = self.kwargs['pk']
            declaracion_obj = Declaraciones.objects.filter(
                folio=uuid.UUID(folio_declaracion),
                info_personal_fija__usuario=self.request.user
                ).first()
            registros = self.model.objects.filter(
                pk=pk,
                declaraciones=declaracion_obj
                ).first()
        except Exception as e:
            print (e)
            raise Http404("")
        return registros

    def delete(self, request, *args, **kwargs):
        self.get_object().delete()
        return JsonResponse({'delete': 'ok'})

declaraciones/templates/declaracion/direccion.html
{% load static %}
{% load bootstrap4 %}
<div class="col-md-4">
    {% include 'layout/nacionalidad.html' with field=form.cat_pais label="Lugar donde se ubica" pais=pais%}
</div>
<div class="col-md-4">
    <div class="form-group">
        <label for="cargo-entidad" class="label-secondary">Entidad federativa{% if entidad %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
        <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="Lugar donde se encuentra actualmente.">
            <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
        </button>
        {% bootstrap_field form.cat_entidades_federativas   field_class='entidad'   show_label=False%}
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label for="cargo-municipio" class="label-secondary">Municipio{% if municipio %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
        <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="Municipio donde se ubica actualmente.">
            <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
        </button>
        {% bootstrap_field form.municipio   show_label=False placeholder="Municipio" %}
    </div>
</div>
<div class="col-md-4">
    <div class="w-50">
        <div class="form-group">
            <label for="cargo-cp" class="label-secondary">Código postal{% if cp %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
            <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="Código postal donde se ubica.">
                <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
            </button>
           {% bootstrap_field form.cp   show_label=False placeholder="Código postal"  field_class='valida_cp'  %}
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label for="cargo-colonia" class="label-secondary">Colonia{% if colonia %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
        <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="Colonia donde se ubica.">
            <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
        </button>
        {% bootstrap_field form.colonia   show_label=False placeholder="Colonia" %}
    </div>
</div>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="cargo-tipo-via" class="label-secondary">Tipo de vía{% if tipo_via %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
                <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="calle/avenida/cerrada/callejón/etc.">
                    <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
                </button>
                <div class="form-group">
                    <label class="sr-only" for="id_entidad">TIPO DE VIA</label>
                    {% bootstrap_field form.cat_tipo_via   show_label=False placeholder="Tipo de vía" %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="cargo-via" class="label-secondary">Nombre de la vía{% if nombre_via %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
                <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="Nombre de la vía donde se ubica.">
                    <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
                </button>
               {% bootstrap_field form.nombre_via   show_label=False placeholder="Nombre de la vía" %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="cargo-no-ext" class="label-secondary">Número exterior{% if exterior %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
                        <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="Número exterior donde se ubica.">
                            <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
                        </button>
                        {% bootstrap_field form.num_exterior   show_label=False placeholder="Número exterior" %}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="cargo-no-int" class="label-secondary">Número interior{% if interior %}<span class="text-danger text-lg font-weight-bold">*</span>{% endif %}</label>
                        <button type="button" class="btn btn-link p-0 btn-information" data-toggle="tooltip" tabindex="9999"  title="Número interior donde se ubica.">
                            <img src="{% static 'src/img/info.svg'%}" alt="info" class="svg">
                        </button>
                         {% bootstrap_field form.num_interior   show_label=False placeholder="Número interior" %}
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

declaraciones/templates/declaracion/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<section class="container">
    <div class="row row-md my-7 py-7">
      <div class="col-12 mb-5">
          <h1 class="text-gray text-xl font-weight-medium text-uppercase line-height-md title-mobile text-mobile"><span class="text-primary-light font-weight-semibold hyphen-auto">{{ user.first_name|upper}}</span> selecciona el<br> tipo de <span class="text-primary-light font-weight-semibold">declaración</span><br> que deseas realizar</h1>
      </div>
      <div class="col-md-6 mb-5">
        <a href="{% url 'declaracion:informacion-general' 1 %}" class="btn btn-secondary btn-block btn-lg font-weight-semibold">DECLARACIÓN INICIAL</a>
        <p class="mt-2 text-primary-light text-md">Realízala si estas dentro de los 60 días naturales a tu ingreso o reingreso al servicio público.</p>
      </div>
      <div class="col-md-6 mb-5">
        <a href="{% url 'declaracion:informacion-general' 2 %}" class="btn btn-secondary btn-block btn-lg font-weight-semibold">DECLARACIÓN ANUAL</a>
        <p class="mt-2 text-primary-light text-md">Realízala durante el mes de mayo de cada año,siempre y cuando estes activo en el servicio público y ya hayas realizado una declaración inicial.</p>
      </div>
      <div class="col-md-6 mb-5">
        <a href="{% url 'declaracion:informacion-general' 4 %}" class="btn btn-secondary btn-block btn-lg font-weight-semibold">DECLARACIÓN DE ACTUALIZACIÓN</a>
        <p class="mt-2 text-primary-light text-md">Puedes realizarla en cualquier momento en que consideres oportuno actualizar un posible conflicto de interés, tu nivel académico o experiencia laboral.</p>
      </div>
      <div class="col-md-6 mb-5">
        <a href="{% url 'declaracion:informacion-general' 3 %}" class="btn btn-secondary btn-block btn-lg font-weight-semibold">DECLARACIÓN DE CONCLUSIÓN</a>
        <p class="mt-2 text-primary-light text-md">Realízala dentro de los siguientes 60 días naturales a la conclusión de tu encargo en el servicio público.</p>
      </div>
    </div>

{% if declaracion is not None %}

<div class="modal fade" id="modal-aviso-declaracion-activa" tabindex="-1" role="dialog" aria-hidden="true"  data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-body text-center">
        <a href="{% url 'declaracion:informacion-general' declaracion.folio %}">
          <img src="{% static 'src/img/close.svg' %}" alt="Cerrar" class="svg">
        </a><br/><br/>
        <p class="text-lg w-75 mb-7 mx-auto">NO PUEDES INICIAR UNA NUEVA DECLARACIÓN PORQUE TIENES UNA EN CURSO.<br/><br/>
            <a href="{% url 'declaracion:informacion-general' declaracion.folio %}"
                 class="btn btn-success-lighter">
                            <span class="texto-chico-boton">IR A LA DECLARACIÓN EN CURSO</span>
            </a>

        </p>



      </div>
    </div>
  </div>
</div>


{% endif %}

</section>
{% endblock %}

declaraciones/templates/declaracion/registro.html
{% include 'layout/headertop.html' %}
{% load bootstrap4 %}
<section class="container-fluid container-offset-x my-md-7 py-7">
  <h1 class="text-gray text-xl font-weight-medium text-uppercase line-height-md">Por favor ingresa la <br> información para <br> <span class="text-primary-light font-weight-semibold">crear tu cuenta</span></h1>
  <p class="text-gray-darker font-weight-light">Todos lo campos son obligatorios</p>
  <form action="{% if is_staff %}{% url 'declaracion:nuevo-usuario' %}{% else %}{% url 'declaracion:nuevo' %}{% endif %}" method="post" novalidate>
    {% csrf_token %}
    <div class="row">
      <div class="col-lg-10">
        <div class="row">
          <div class="col-md-6">
            {% bootstrap_field form.nombres placeholder="Nombre(s)" field_class="solo_letras"  %}
          </div>
          <div class="col-md-6">
              {% bootstrap_field form.apellido1 placeholder="Primer Apellido" field_class="solo_letras"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.apellido2 placeholder="Segundo apellido" field_class="solo_letras" required=False  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.rfc placeholder="RFC con homoclave" field_class='valida_rfc'  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.curp placeholder="CURP"  field_class='valida_curp' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.dependencia placeholder="Ente público"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.puesto placeholder="Empleo, cargo o comisión" field_class="solo_letras" %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.fecha placeholder="16/01/2018"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.entidad placeholder="Entidad Federativa" field_class="entidad"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.pais placeholder="País de origen" field_class="pais"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.contrasena1 placeholder="Contraseña"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.telefono placeholder="Teléfono" field_class="valida_telefono"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.contrasena2 placeholder="Confirmar Contraseña"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.email placeholder="Correo electrónico" field_class='valida_email'  %}
          </div>
          <div class="col-12 text-right">
            <button type="submit" class="btn btn-success-lighter text-uppercase mt-5">Crear cuenta</button>
          </div>
        </div>
      </div>
    </div>
  </form>
</section>
{% include 'layout/footer.html' %}