declaraciones/declaraciones/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls import include, url
from declaracion import urls
from sitio import urls


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('declaracion/', include('declaracion.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

declaraciones/sitio/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy, re_path

from sitio.views import LoginView, LogoutView, CambioPasswordView, PasswordResetRFCView,activar
from .views import (IndexView, FAQsView, InformacionView,
                    DeclaracionesPreviasView,
                    DeclaracionesPreviasDescargarView)
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('preguntas-frecuentes', FAQsView.as_view(), name="preguntas-frecuentes"),
    path('informacion', InformacionView.as_view(), name="informacion"),
    path('declaraciones-previas', DeclaracionesPreviasView.as_view(), name="declaraciones-previas"),
    re_path(r'^declaraciones-previas/descargar/(?P<folio>[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})/$',
            DeclaracionesPreviasDescargarView.as_view(),
            name="declaraciones-previas-descargar"),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('recuperar', LogoutView.as_view(), name="recuperar"),
    path('cambiar', CambioPasswordView.as_view(), name="cambiar"),
    path('password_reset/', PasswordResetRFCView.as_view(success_url=reverse_lazy('password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^activar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activar, name='activar')
]

declaraciones/declaracion/models/pasivos.py
from django.db import models
from django.urls import reverse_lazy
from .informacion_personal import(Declaraciones, Domicilios, Observaciones, InfoPersonalVar)
from .catalogos import (CatTiposPasivos, CatTiposOperaciones, CatTiposAcreedores,
                        CatTiposAdeudos, CatPaises, CatSectoresIndustria,
                        CatMonedas, CatTiposTitulares, CatUnidadesTemporales)


class DeudasOtros(models.Model):
    otra_operacion = models.CharField(max_length=255, blank=True)
    otro_tipo_acreedor = models.CharField(max_length=255, blank=True)
    otro_tipo_adeudo = models.CharField(max_length=255, blank=True)
    numero_cuenta = models.CharField(max_length=255, blank=True)
    fecha_generacion = models.DateField(null=True, blank=True)
    monto_original = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    tasa_interes = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    saldo_pendiente = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    monto_abonado = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    plazo = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, default=0)
    otro_titular = models.CharField(max_length=255, blank=True)
    porcentaje_adeudo = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    garantia = models.BooleanField(blank=True, null=True, default=None)
    nombre_garantes = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_monedas = models.ForeignKey(CatMonedas, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_paises = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipos_acreedores = models.ForeignKey(CatTiposAcreedores, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipos_adeudos = models.ForeignKey(CatTiposAdeudos, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipos_operaciones = models.ForeignKey(CatTiposOperaciones, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipos_pasivos = models.ForeignKey(CatTiposPasivos, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipos_titulares = models.ForeignKey(CatTiposTitulares, on_delete=models.DO_NOTHING, null=True, blank=True)
    declaraciones = models.ForeignKey(Declaraciones, on_delete=models.DO_NOTHING)
    observaciones = models.ForeignKey(Observaciones, on_delete=models.DO_NOTHING)
    acreedor_infopersonalvar = models.ForeignKey(InfoPersonalVar, on_delete=models.DO_NOTHING)
    cat_unidades_temporales = models.ForeignKey(CatUnidadesTemporales, on_delete=models.DO_NOTHING, null=True, blank=True)
    def observacion(self):
        return [self.observaciones]
    def persona(self):
        return [self.acreedor_infopersonalvar]

    def columna_uno(self):
        if self.cat_tipos_operaciones:
            return u"{}".format(self.cat_tipos_operaciones)
        else:
            return u""

    def columna_dos(self):
        if self.cat_tipos_acreedores:
            return u"{}".format(self.cat_tipos_acreedores)
        else:
            return u""

    def columna_tres(self):
        if self.cat_tipos_adeudos:
            return u"{}".format(self.cat_tipos_adeudos)
        else:
            return u""

    def url(self):
        if self.cat_tipos_pasivos_id == 1:
            return u"deudas"
        else:
            return u"deudas-otros"

    def url_editar(self):
            return reverse_lazy('declaracion:' + self.url() + '-editar',
                                kwargs={'folio': self.declaraciones.folio,
                                        'pk': self.id})

    def url_borrar(self):
        return reverse_lazy('declaracion:' + self.url() + '-borrar',
                            kwargs={'folio': self.declaraciones.folio,
                                    'pk': self.id})

    def url_todos(self):
        return reverse_lazy('declaracion:' + self.url() + '',
                            kwargs={'folio': self.declaraciones.folio})

    def tipo_operacion(self):
        try:
            if self.cat_tipos_operaciones.default:
                return u"{} {}".format(self.cat_tipos_operaciones,
                                       self.otra_operacion)
            else:
                return u"{}".format(self.cat_tipos_operaciones)
        except Exception as e:
            return u""

    def tipo_acreedor(self):
        try:
            if self.cat_tipos_acreedores.default:
                return u"{} {}".format(self.cat_tipos_acreedores,
                                       self.otro_tipo_acreedor)
            else:
                return u"{}".format(self.cat_tipos_acreedores)
        except Exception as e:
            return u""

    def tipo_adeudo(self):
        try:
            if self.cat_tipos_adeudos.default:
                return u"{} {}".format(self.cat_tipos_adeudos,
                                       self.otro_tipo_adeudo)
            else:
                return u"{}".format(self.cat_tipos_adeudos)
        except Exception as e:
            return u""

    def titular(self):
        try:
            if self.cat_tipos_titulares.default:
                return u"{} {}".format(self.cat_tipos_titulares,
                                       self.otro_titular)
            else:
                return u"{}".format(self.cat_tipos_titulares)
        except Exception as e:
            return u""

declaraciones/declaracion/forms/admin.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

from declaracion.models import CatTiposDeclaracion, InfoPersonalVar, InfoPersonalFija
from declaracion.models.catalogos import CatEntesPublicos, CatEstatusDeclaracion


class BusquedaDeclaranteForm(forms.Form):
    nombre = forms.CharField(max_length=128,label="Nombre", required=False )
    apellido1 = forms.CharField(max_length=128,label="Primer Apellido", required=False )
    apellido2 = forms.CharField(max_length=128,label="Segundo Apellido", required=False )
    rfc = forms.CharField(max_length=13,label="RFC", required=False,validators=[RegexValidator('^([A-Z,Ñ,&]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[A-Z|\d]{3})$', message="Introduzca un RFC válido")] )
    curp = forms.CharField(max_length=18,label="CURP", required=False )
    ente = forms.ModelChoiceField(queryset=CatEntesPublicos.objects.all(),required=False,label="Ente público")
    estatus = forms.ModelChoiceField(queryset=CatEstatusDeclaracion.objects.all(),required=False,label="Estatus")
    page = forms.CharField(widget=forms.HiddenInput(), required=False)
    page_size = forms.CharField(widget=forms.HiddenInput(), required=False,initial="10" )
class BusquedaUsuariosForm(forms.Form):
    TRUE_FALSE_CHOICES = (
        (None,'--------'),
        (True, 'Activo'),
        (False, 'Inactivo')
    )

    nombre = forms.CharField(max_length=128,label="Nombre", required=False )
    apellido1 = forms.CharField(max_length=128,label="Primer Apellido", required=False )
    apellido2 = forms.CharField(max_length=128,label="Segundo Apellido", required=False )
    ente = forms.ModelChoiceField(queryset=CatEntesPublicos.objects.all(),required=False)
    estatus = forms.ChoiceField(choices = TRUE_FALSE_CHOICES, label="Estatus",
                              initial='', widget=forms.Select(), required=False)
    page = forms.CharField(widget=forms.HiddenInput(), required=False)
    page_size = forms.CharField(widget=forms.HiddenInput(), required=False,initial="10")

class BusquedaDeclaracionForm(forms.Form):
    folio = forms.CharField(max_length=128,label="Folio", required=False )
    tipo = forms.ModelChoiceField(queryset=CatTiposDeclaracion.objects.all(),label="Tipo de declaración", required=False )
    ente = forms.ModelChoiceField(queryset=CatEntesPublicos.objects.all(),label="Ente público", required=False )
    ano = forms.IntegerField(label="Año", required=False )
    estatus = forms.ModelChoiceField(queryset=CatEstatusDeclaracion.objects.all(),label="Estatus", required=False )
    page = forms.CharField(widget=forms.HiddenInput(), required=False)
    page_size = forms.CharField(widget=forms.HiddenInput(), required=False,initial="10")


class RegistroUsuarioForm(forms.Form):
    roles = (
        (False, 'Operador'),
        (True, 'Administrador')
    )
    estatus = (
        (True, 'Activo'),
        (False, 'Inactivo')
    )

    nombres = forms.CharField(required = True,label="Nombre(s)")
    apellido1 = forms.CharField(required = True,label="Primer apellido")
    apellido2 = forms.CharField(required = False,label="Segundo apellido")
    dependencia = forms.ModelChoiceField(queryset=CatEntesPublicos.objects.all(),required = True,label="Ente público")
    telefono = forms.CharField(max_length=15,required = True,label="Teléfono",validators=[RegexValidator('^\+?1?\d{9,10}$', message="Introduzca un Teléfono válido")])
    rfc = forms.CharField(max_length=13, label="RFC con Homoclave", required=True,validators=[RegexValidator('^([A-Z,Ñ,&]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[A-Z|\d]{3})$', message="Introduzca un RFC válido")])
    puesto = forms.CharField(required = True,label="Empleo, cargo o comisión")
    email = forms.EmailField(required=True, label="Correo electrónico")
    rol =  forms.ChoiceField(choices=roles)
    estatus =  forms.ChoiceField(choices=estatus)
    id = forms.CharField(widget=forms.HiddenInput(),required=False)

    def clean(self):
        super().clean()

        try:
            id =int(self.cleaned_data.get("id"))
        except:
            id=None


        email = self.cleaned_data.get("email")
        email = str(email).lower()
        if id is None:
            if User.objects.filter(email = email).count()>0:
                self.add_error("email","Correo ya registrado")
        else:
            if User.objects.filter(email = email).exclude(pk=id).count()>0:
                self.add_error("email","Correo ya registrado")


        rfc = self.cleaned_data.get("rfc")
        rfc = str(rfc).upper()
        if id is None:
            if User.objects.filter(username = rfc).count()>0:
                self.add_error("rfc","RFC ya registrado")
        else:
            if User.objects.filter(username = rfc,pk=id).exclude(pk=id).count()>0:
                self.add_error("rfc","RFC ya registrado")

declaraciones/declaracion/views/api.py
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views import View

from declaracion.models import Declaraciones
from datetime import datetime
from django.core.paginator import Paginator
from django.shortcuts import render

class RegistrosView(View):
    template_name = "reportes/publico.json.html"


    def get(self, request, *args, **kwargs):
        api_key = request.GET.get('api_key')
        sort = request.GET.get('sort')
        page = request.GET.get('page')
        page_size = request.GET.get('page_size')
        nombres = request.GET.get('nombres')
        apellido1 = request.GET.get('apellido1')
        apellido2 = request.GET.get('apellido2')
        rfc = request.GET.get('rfc')
        curp = request.GET.get('rfc')

        id = request.GET.get('id')
        actualizacion = request.GET.get('actualizacion')
        rfc_solicitante = request.GET.get('rfc_solicitante')
        filter = False


        declaraciones = Declaraciones.objects
        if id and id != "":
            declaraciones = declaraciones.filter(folio=id)
            filter=True
        if rfc and rfc != "":
            declaraciones = declaraciones.filter(info_personal_fija__rfc=rfc.upper())
            filter=True
        if curp and curp != "":
            declaraciones = declaraciones.filter(info_personal_fija__curp=curp.upper())
            filter = True
        if nombres and nombres != "":
            declaraciones = declaraciones.filter(info_personal_fija__nombres__contains=nombres.upper())
            filter = True
        if apellido1 and apellido1 != "":
            declaraciones = declaraciones.filter(info_personal_fija__apellido1__contains=apellido1.upper())
            filter = True
        if apellido2 and apellido2 != "":
            declaraciones = declaraciones.filter(info_personal_fija__apellido2__contains=apellido2.upper())
            filter = True
        if sort and sort.upper() == "ASC":
            declaraciones = declaraciones.order_by('fecha_declaracion')
            filter = True
        elif sort and sort.upper() == "DESC":
            declaraciones = declaraciones.order_by('-fecha_declaracion')
            filter = True
        if actualizacion and actualizacion != "":
            actualizacion = datetime.strptime(actualizacion, "%Y-%m-%d")
            declaraciones = declaraciones.filter(fecha_declaracion__gte=actualizacion)
            filter = True
        if not filter:
            declaraciones=declaraciones.all()

        if page_size and page:
            paginator = Paginator(declaraciones, int(page_size))
            declaraciones = paginator.get_page(int(page))
        response = render_to_string(self.template_name, {
            'declaraciones': declaraciones
        })
        return HttpResponse(content = response,content_type="application/json")

declaraciones/declaracion/views/declaracion.py
import uuid
import json
from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView
from django.http import Http404, JsonResponse
from declaracion.models import Declaraciones,InfoPersonalFija
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Q

class DeclaracionView(TemplateView):
    template_name = "declaracion/index.html"
    @method_decorator(login_required(login_url='/login'))
    def get(self,request,*args,**kwargs):
        try:
            declaracion = Declaraciones.objects.filter(
                info_personal_fija=InfoPersonalFija.objects.filter(usuario=request.user).first()).filter(
                Q(cat_estatus__isnull=True) | Q(cat_estatus__pk__in=(1, 2, 3))).first()

        except:
            declaracion = None

        return render(request,self.template_name,{'declaracion':declaracion})


class DeclaracionDeleteView(DeleteView):
    def get(self, request, *args,**kwargs):
        raise Http404("")

    def get_object(self, queryset=None):
        try:
            folio_declaracion = self.kwargs['folio']
            pk = self.kwargs['pk']
            declaracion_obj = Declaraciones.objects.filter(
                folio=uuid.UUID(folio_declaracion),
                info_personal_fija__usuario=self.request.user
                ).first()
            registros = self.model.objects.filter(
                pk=pk,
                declaraciones=declaracion_obj
                ).first()
        except Exception as e:
            print (e)
            raise Http404("")
        return registros

    def delete(self, request, *args, **kwargs):
        self.get_object().delete()
        return JsonResponse({'delete': 'ok'})

declaraciones/templates/declaracion/admin/busqueda-declaraciones.html
{% include 'layout/headertop.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <form action="{% url 'declaracion:busqueda-declaraciones' %}" method="post" id="form">
<section class="container">
  <div class="row row-md ">
    <h1 class="text-gray text-xl font-weight-medium text-uppercase mt-5 line-height-md title-mobile text-mobile"><span class="text-primary-light font-weight-semibold">DECLARACIONES</span> Búsqueda</h1>
    <div class="d-flex justify-content-center align-items-center flex-column flex-sm-row bg-gray p-4 rounded">
               {% csrf_token %}
               {%  bootstrap_field form.page %}
               <div class="row">
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.folio  %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.tipo  field_class="solo_letras" %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       <label> Ente público</label>
                       {% bootstrap_field form.ente show_label=False %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.ano    %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">

                       {% bootstrap_field form.estatus %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 ">
                       <button class="btn btn-success-lighter text-uppercase font-weight-semibold mt-5"  type="submit">Buscar  <img src="{% static 'src/img/busqueda.svg' %}"/></button>
                   </div>
               </div>
    </div>
  </div>
 {% if result %}
  <div class="row row-md">

        <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">ENTE PÚBLICO</th>
                  <th scope="col">CARGO</th>
                  <th scope="col">PLAZO DE REALIZACIÓN</th>
                  <th scope="col">FECHA DE FIRMA</th>
                  <th scope="col">INICIO DE CARGO</th>
                  <th scope="col">FIN DE CARGO</th>
                  <th scope="col">VER DECLARACIÓN</th>
                </tr>
              </thead>
              <tbody>
              {% for r in result %}

              {% for p in r.encargos_set.all %}
                <tr>
                  <th scope="row">{{ p.cat_entes_publicos }}</th>
                  <td>{{ p.empleo_cargo_comision }}</td>
                  <td>{{ r.fecha_declaracion }}</td>
                  <td>{{ r.fecha_declaracion }}</td>
                  <td>{{ p.posesion_inicio }}</td>
                  <td>{{ p.posesion_conclusion }}</td>
                  <td><a href="{%  url 'declaracion:info-declaracion' r.pk %}"> <img src="{% static 'src/img/contar2.svg' %}"></a></td>
                </tr>
              {% endfor %}
              {% endfor %}
              </tbody>
        </table>





  </div>

<div class="row row-md text-center">
<div class="col-12">
 	<nav aria-label="Páginas" class="nav d-flex justify-content-center">
	  <ul class="pagination flex-wrap">
		{% if result.has_previous %}
		<li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ result.previous_page_number }});$('#form').submit()" href="#">«</a></li>
		 {% endif %}

						{%for p in paginas%}
							{%ifequal p result.number %}
								<li class="page-item"><a class="page-link bg-primary text-light" href="#">{{result.number}}</a></li>
							{%else%}
								<li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ p }});$('#form').submit()" href="#">{{p}}</a></li>
							{%endifequal%}
						{%endfor%}
		 {% if result.has_next %}
		<li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ result.next_page_number }});$('#form').submit()" href="#">»</a></li>
		  {%endif%}

	  </ul>
	</nav>
</div>
    <!--<div class="col-12 text-center">
  	    <span>Página {{ result.number }} de {{ result.paginator.num_pages }}.</span>
    </div>-->



</div>

 {% endif %}

</section>
    </form>
{% endblock %}
{% include 'layout/footer.html' %}

declaraciones/templates/declaracion/admin/busqueda-declarantes.html
{% include 'layout/headertop.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <form action="{% url 'declaracion:busqueda-declarantes' %}" method="post" id="form">
<section class="container">
  <div class="row row-md ">
    <h1 class="text-gray text-xl font-weight-medium text-uppercase mt-5 line-height-md title-mobile text-mobile"><span class="text-primary-light font-weight-semibold">Declarantes</span> Búsqueda</h1>
    <div class="d-flex justify-content-center align-items-center flex-column flex-sm-row bg-gray p-4 rounded">


               {% csrf_token %}
               {% bootstrap_field form.page  show_label=False%}
               <div class="row">
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.nombre  field_class="solo_letras"  %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.apellido1  field_class="solo_letras" %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.apellido2  field_class="solo_letras" %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.rfc  field_class="valida_rfc" %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       <label > Ente público</label>
                       {% bootstrap_field form.ente show_label=False %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.curp    field_class="valida_curp" %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                       {% bootstrap_field form.estatus  %}
                   </div>
                   <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 ">
                       <button class="btn btn-success-lighter text-uppercase font-weight-semibold mt-5"  type="submit">Buscar  <img src="{% static 'src/img/busqueda.svg' %}"/></button>
                   </div>


               </div>



    </div>
  </div>
 {% if result %}
  <div class="row row-md">

        <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">NOMBRE</th>
                  <th scope="col">PRIMER APELLIDO</th>
                  <th scope="col">SEGUNDO APELLIDO</th>
                  <th scope="col">RFC</th>
                  <th scope="col">CURP</th>
                  <th scope="col">ESTATUS</th>
                  <th scope="col">VER DETALLE</th>
                </tr>
              </thead>
              <tbody>
              {% for r in result %}
                <tr>
                  <th scope="row">{{ r.nombres }}</th>
                  <td>{{ r.apellido1 }}</td>
                  <td>{{ r.apellido2 }}</td>
                  <td>{{ r.rfc }}</td>
                  <td>{{ r.curp }}</td>
                  <td>{% if r.usuario.is_active %} <span class="text-primary-light">Activo</span> {% else %} Inactivo {% endif %} </td>
                  <td><a href="{%  url 'declaracion:info-declarante' r.pk %}"> <img src="{% static 'src/img/reconocimiento-facial-2.svg' %}"></a></td>
                </tr>
              {% endfor %}
              </tbody>
        </table>





  </div>

<div class="row row-md text-center">
<div class="col-12">
 	<nav aria-label="Páginas" class="nav d-flex justify-content-center">
	  <ul class="pagination flex-wrap">
		{% if result.has_previous %}
		<li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ result.previous_page_number }});$('#form').submit()" href="#">«</a></li>
		 {% endif %}

						{%for p in paginas%}
							{%ifequal p result.number %}
								<li class="page-item"><a class="page-link bg-primary text-light" href="#">{{result.number}}</a></li>
							{%else%}
								<li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ p }});$('#form').submit()" href="#">{{p}}</a></li>
							{%endifequal%}
						{%endfor%}
		 {% if result.has_next %}
		<li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ result.next_page_number }});$('#form').submit()" href="#">»</a></li>
		  {%endif%}

	  </ul>
	</nav>
</div>

    <!--<div class="col-12 text-center">
  	    <span>Página {{ result.number }} de {{ result.paginator.num_pages }}.</span>
    </div>-->



</div>

 {% endif %}

</section>
    </form>
{% endblock %}
{% include 'layout/footer.html' %}

declaraciones/templates/declaracion/admin/frm_domicilio.html
<h6 class="text-success-lighter p_opciones mb-0">Domicilio</h6>
<dl class="p_opciones">
  <dt>Código postal</dt>
  <dd class="text-black_opciones">{{ domicilio.cp|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>País</dt>
  <dd class="text-black_opciones">{{ domicilio.cat_pais|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Entidad federativa</dt>
  <dd class="text-black_opciones">{{ domicilio.cat_entidades_federativas|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Municipio</dt>
  <dd class="text-black_opciones">{{ domicilio.municipio|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Colonia</dt>
  <dd class="text-black_opciones">{{ domicilio.colonia|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Tipo de vía</dt>
  <dd class="text-black_opciones">{{ domicilio.cat_tipo_via|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Nombre de vía</dt>
  <dd class="text-black_opciones">{{ domicilio.nombre_via|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Número exterior</dt>
  <dd class="text-black_opciones">{{ domicilio.num_exterior|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Número interior</dt>
  <dd class="text-black_opciones">{{ domicilio.num_interior|default_if_none:"" }}</dd>
</dl>